//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGXEPLOAI
    {
        public int ID { get; set; }
        public Nullable<double> DIEM { get; set; }
        public string XEPLOAI { get; set; }
    }
}
