//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOPHAN_SDT
    {
        public int ID { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<int> BP { get; set; }
    
        public virtual BOPHAN BOPHAN { get; set; }
    }
}
