//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANBO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CANBO()
        {
            this.TRANGTHAIDANGNHAPs = new HashSet<TRANGTHAIDANGNHAP>();
            this.SOTHUTUs = new HashSet<SOTHUTU>();
        }
    
        public int MACB { get; set; }
        public string HOTEN { get; set; }
        public Nullable<int> MABP { get; set; }
        public string HINHANH { get; set; }
        public string ID { get; set; }
        public string PW { get; set; }
    
        public virtual BOPHAN BOPHAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANGTHAIDANGNHAP> TRANGTHAIDANGNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOTHUTU> SOTHUTUs { get; set; }
    }
}
