//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOPY
    {
        public int MAGY { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> MADG { get; set; }
    
        public virtual KETQUADANHGIA KETQUADANHGIA { get; set; }
    }
}
