//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINNHAN
    {
        public int ID { get; set; }
        public Nullable<int> SDT { get; set; }
        public Nullable<bool> BP1 { get; set; }
        public Nullable<bool> BP2 { get; set; }
        public Nullable<bool> BP3 { get; set; }
        public Nullable<bool> BP4 { get; set; }
        public Nullable<bool> BP5 { get; set; }
        public Nullable<bool> BP6 { get; set; }
        public Nullable<bool> BP7 { get; set; }
        public Nullable<bool> BP8 { get; set; }
        public Nullable<bool> BP9 { get; set; }
        public Nullable<bool> BP10 { get; set; }
        public Nullable<bool> BP11 { get; set; }
        public Nullable<bool> BP12 { get; set; }
        public Nullable<bool> BP13 { get; set; }
        public Nullable<bool> BP14 { get; set; }
        public Nullable<bool> BP15 { get; set; }
    
        public virtual SODIENTHOAI SODIENTHOAI { get; set; }
    }
}
