//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServerAPI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANGTHAIDANGNHAP
    {
        public int MADN { get; set; }
        public Nullable<int> MACB { get; set; }
        public Nullable<int> MAMAY { get; set; }
        public Nullable<System.DateTime> BD { get; set; }
        public Nullable<System.DateTime> KT { get; set; }
    
        public virtual MAYDANHGIA MAYDANHGIA { get; set; }
        public virtual CANBO CANBO { get; set; }
    }
}
